# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: annahurtovenko/kbot
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.0-c866920-arm64-3df0b50"
  arch: "amd64"
  os: linux
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
