name: KBOT-CICD

on:
  push:
    branches:
      - develop

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
  
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
            contents: read
            packages: write

    steps:                          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dckr_pat_pqN6NS41BAugxSiGjxyh0Hb14jk
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}


      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: "${{ env.REGISTRY }}/${{ github.actor }}"
        run: make image push 
      
  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "update version $VERSION"
        git push
